import type { Metadata } from "next";
import "./globals.css";
import "@/styles/variables.css";
import localFont from "next/font/local";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { AuthProvider, ToastProvider } from "@/providers";
import FooterWithAuth from "@/components/layout/Footer/FooterWithAuth";
import Header from "@/components/layout/Header";

const workSans = localFont({
  src: [
    {
      path: "../fonts/WorkSansRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/WorkSansBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/WorkSansSemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/WorkSansMedium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "ToolNext",
  description: "Generated by create next app",
  icons: {
    icon: "https://ac.goit.global/fullstack/react/notehub-og-meta.jpg",
  },
  openGraph: {
    title: "ToolNext",
    description: "Generated by create next app",
    url: "https://08-zustand-lyart-mu.vercel.app",
    images: [
      {
        url: "https://ac.goit.global/fullstack/react/notehub-og-meta.jpg",
        width: 1200,
        height: 630,
        alt: "ToolNext",
      },
    ],
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSans.variable}>
        <TanStackProvider>
          <AuthProvider>
            <ToastProvider>
              <Header />
              <main>
                {children}
                {modal}
              </main>
              <FooterWithAuth />
            </ToastProvider>
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
